### ISSUE TITLE
Does not work on current Windows 11 version

### ISSUE THREAD

**Issue by EemeIi** [mogya/win-11-virtual-desktop-enhancer#2]
Hey! Your fork does not work for me on Windows 11, version 21H2 (OS Build 22000.1098). Nothing happens when I try to switch desktops.

**Comment by schmiddd** [comment]
same here. KeyboardShortcutsCombinations as RenameDesktop are fine, but KeyboardShortcutsModifiers + Identifiers won't work.

**Comment by mogya** [comment]
(Sorry I found this issue today.)
I'm working SwitchDesktop function with Win+1,2..., and at least one more guy get working fine also. 
You may need to modify setting.ini file?
